### ISSUE TITLE
Error: Definition for rule 'no-tabs-in-file' was not found.

### ISSUE THREAD

**Issue by mondalaci** [gyandeeps/eslint-plugin-ideal#1]
After `npm install -g eslint-plugin-ideal` I included `"no-tabs-in-file": 1` into `~/.eslintrc`: under the `rules` key and upon executing `eslint` got:

```
/usr/lib/node_modules/eslint/lib/eslint.js:647
                    throw new Error("Definition for rule '" + key + "' was not
                          ^
Error: Definition for rule 'no-tabs-in-file' was not found.
    at /usr/lib/node_modules/eslint/lib/eslint.js:647:27
    at Array.forEach (native)
    at EventEmitter.module.exports.api.verify (/usr/lib/node_modules/eslint/lib/eslint.js:620:16)
    at processFile (/usr/lib/node_modules/eslint/lib/cli-engine.js:197:27)
    at /usr/lib/node_modules/eslint/lib/cli-engine.js:332:26
    at /usr/lib/node_modules/eslint/lib/util/traverse.js:61:17
    at Array.forEach (native)
    at traverse (/usr/lib/node_modules/eslint/lib/util/traverse.js:41:54)
    at walk (/usr/lib/node_modules/eslint/lib/util/traverse.js:83:9)
    at /usr/lib/node_modules/eslint/lib/util/traverse.js:102:9
```

What can be the problem?

**Comment by gyandeeps** [comment]
You have to install the plugin where eslint is installed. If eslint is global then plugin should be global too.
If local then both should be local.
Can you share your eslint config file?

**Comment by mondalaci** [comment]
Both eslint and your plugin are global. Here's my `.eslintrc`:

```
{
    "env": {
        "browser": true
    },
    "rules": {
        "key-spacing": 0,
        "new-cap": [2, {
            "capIsNewExceptions": ["CodeMirror", "Event", "Workflow"]
        }],
        "no-multi-spaces": 0,
        "no-use-before-define": 0,
        "space-after-keywords": [2, "always"],
        "space-before-function-paren": [2, "never"],
        "space-infix-ops": 0,
        "strict": [2, "function"],
        "quotes": [2, "single", "avoid-escape"],
        "yoda": 0,
        "no-tabs-in-file": 1 
    },
    "globals": {
        "_gaq": false,
        "AccessUser": false,
        "Accordion": false,
        "applySmartDrop": false,
        "AnalysisTableGenerator": false,
        "angular": false,
        "basicInfo": false,
        "billingInfo": false,
        "BrowserDetect": false,
        "ClientsideFilterAbstract": false,
        "ClientsideFilterDuplicate": false,
        "CodeMirror": false,
        "ContractIndexSelectorComponent": false,
        "DashboardContext": false,
        "DashboardCSSEditor": false,
        "DashboardJavascriptEditor": false,
        "DashboardrowSaveController": false,
        "dialog": false,
        "DialogComponent": false,
        "DialogController": false,
        "discoveryPageController": false,
        "DiscoveryPagePresenter": false,
        "EncodeUtil": false,
        "FEATURE_ALL": false,
        "FEATURE_ALL_KEY": false,
        "FeatureAdder": false,
        "featureToPrivileges": false,
        "flag": false,
        "IndexRange": false,
        "labs": false,
        "languageDropdowns": false,
        "log": false,
        "messages": false,
        "moment": false,
        "multiLanguageSelector": false,
        "ngApp": false,
        "pathInfo": false,
        "permissionHandler": false,
        "preselectionHandler": false,
        "productInfo": false,
        "project": false,
        "ProjectFeature": false,
        "projectInfo": false,
        "ProjectPrivilege": false,
        "Pusher": false,
        "R": false,
        "S": false,
        "saveAs": false,
        "services": false,
        "StringBuilder": false,
        "StringSet": false,
        "TranslationServiceProviderMap": false,
        "ui": false,
        "URI": false,
        "util": false,
        "VIEWMODE": false,
        "WFRoleSelector": false,
        "Workflow": false,
        "Zenbox": false,
        "$": false,
        "$A": false,
        "$AC": false,
        "$B": false,
        "$D": false,
        "$DA": false,
        "$DD": false,
        "$EL": false,
        "$ELL": false,
        "$F": false,
        "$GD": false,
        "$K": false,
        "$PA": false,
        "$PF": false,
        "$PL": false,
        "$Q": false,
        "$R": false,
        "$RL": false,
        "$S": false
    }
}
```

**Comment by gyandeeps** [comment]
Your configuration is incorrect.
Plugins: http://eslint.org/docs/user-guide/configuring#configuring-plugins
Rules: http://eslint.org/docs/user-guide/configuring#configuring-rules

basically you should also have this

``` js
"plugins": [
    "eslint-plugin-ideal"
],
"rules":{
    "ideal/no-tabs-in-file": 2
}
```

**Comment by mondalaci** [comment]
Thanks a ton, working like a treat!

**Comment by gyandeeps** [comment]
@mondalaci I have updated the docs for rules and added some more rules in version `0.1.0`

**Comment by mondalaci** [comment]
Thanks for letting me know!
